### ISSUE TITLE
How to set lower threshold and upper threshold in 'DetectSurfaces' ?

### ISSUE THREAD

**Issue by LzEfreet** [lacan/EasyXT#2]
emm, It seems like that only one threshold need in function 'DetectSurfaces'.

**Comment by lacan** [comment]
Dear @LzEfreet, 

Indeed this version of EasyXT only allows for a lower threshold to be selectable for surface detection. 

The Imaris Surface Detector does include the option to use the Upper Threshold as well, as per the internal documentation
C:/Program%20Files/Bitplane/Imaris%2010.0.0/html/xtinterface/structImaris_1_1IImageProcessing.html

```
ISurfaces * 	DetectSurfacesRegionGrowingWithUpperThreshold (IDataSet *aDataSet, tInts2D aRegionsOfInterest, int aChannelIndex, float aSmoothFilterWidth, float aLocalContrastFilterWidth, bool aLowerThresholdEnabled, bool aIntensityLowerThresholdAutomatic, float aIntensityLowerThresholdManual, bool aUpperThresholdEnabled, bool aIntensityUpperThresholdAutomatic, float aIntensityUpperThresholdManual, float aSeedsEstimateDiameter, bool aSeedsSubtractBackground, string aSeedsFiltersString, string aSurfaceFiltersString)
 
ISurfaces * 	DetectSurfacesWithUpperThreshold (IDataSet *aDataSet, tInts2D aRegionsOfInterest, int aChannelIndex, float aSmoothFilterWidth, float aLocalContrastFilterWidth, bool aLowerThresholdEnabled, bool aIntensityLowerThresholdAutomatic, float aIntensityLowerThresholdManual, bool aUpperThresholdEnabled, bool aIntensityUpperThresholdAutomatic, float aIntensityUpperThresholdManual, string aSurfaceFiltersString)
```

The relevant function in our code is here
https://github.com/BIOP/EasyXT/blob/7a3547acf1b0dcc5717df9b70e5a4bc8cebcfb1a/EasyXT.m#L1398

Using the structure for adding key value parameters from 
https://github.com/BIOP/EasyXT/blob/7a3547acf1b0dcc5717df9b70e5a4bc8cebcfb1a/EasyXT.m#L1466

You could add a parameter `upperThreshold` and then add another set of `if` statements at https://github.com/BIOP/EasyXT/blob/7a3547acf1b0dcc5717df9b70e5a4bc8cebcfb1a/EasyXT.m#L1510

in order to call `DetectSurfacesWithUpperThreshold`  `DetectSurfacesRegionGrowingWithUpperThreshold`

If you can make a pull request, we would be happy to include it in the code. 

All the best

**Comment by LzEfreet** [comment]
oooh, I see. Thanks for your detailed reply! Problem solved.
